version: "3"
services: 
    app:
        container_name: "FastCut_BackendAPI"
        restart: unless-stopped
        build: .
        ports: 
            - "8080:8000"
        links:
            - mongo
    mongo:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        ports:
             - "27017:27017"
        
