//MUST INSTALL REST Client Extension in order to use this
POST  http://localhost:8000/bookings HTTP/1.1
content-type: application/json
 
{
"customer_name": "Syafisham",  
"customer_phoneNumber": "01126523032",
"status": ["ongoing"]
}